package entity;
// Generated Mar 4, 2019, 5:23:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private BigDecimal addressid;
     private String street;
     private String city;
     private String province;
     private String country;
     private String postcode;
     private Set employees = new HashSet(0);

    public Address() {
    }

	
    public Address(BigDecimal addressid, String street, String city, String province, String country, String postcode) {
        this.addressid = addressid;
        this.street = street;
        this.city = city;
        this.province = province;
        this.country = country;
        this.postcode = postcode;
    }
    public Address(BigDecimal addressid, String street, String city, String province, String country, String postcode, Set employees) {
       this.addressid = addressid;
       this.street = street;
       this.city = city;
       this.province = province;
       this.country = country;
       this.postcode = postcode;
       this.employees = employees;
    }
   
    public BigDecimal getAddressid() {
        return this.addressid;
    }
    
    public void setAddressid(BigDecimal addressid) {
        this.addressid = addressid;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


