package entity;
// Generated Mar 4, 2019, 5:23:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private BigDecimal employeeid;
     private Address address;
     private Employee employee;
     private String firstname;
     private String lastname;
     private BigDecimal salary;
     private Date startdate;
     private Date enddate;
     private Set employees = new HashSet(0);
     private Set proyectos = new HashSet(0);
     private Set projectemployees = new HashSet(0);
     private Set phones = new HashSet(0);

    public Employee() {
    }

	
    public Employee(BigDecimal employeeid, String firstname, String lastname) {
        this.employeeid = employeeid;
        this.firstname = firstname;
        this.lastname = lastname;
    }
    public Employee(BigDecimal employeeid, Address address, Employee employee, String firstname, String lastname, BigDecimal salary, Date startdate, Date enddate, Set employees, Set proyectos, Set projectemployees, Set phones) {
       this.employeeid = employeeid;
       this.address = address;
       this.employee = employee;
       this.firstname = firstname;
       this.lastname = lastname;
       this.salary = salary;
       this.startdate = startdate;
       this.enddate = enddate;
       this.employees = employees;
       this.proyectos = proyectos;
       this.projectemployees = projectemployees;
       this.phones = phones;
    }
   
    public BigDecimal getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(BigDecimal employeeid) {
        this.employeeid = employeeid;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }
    public Set getProjectemployees() {
        return this.projectemployees;
    }
    
    public void setProjectemployees(Set projectemployees) {
        this.projectemployees = projectemployees;
    }
    public Set getPhones() {
        return this.phones;
    }
    
    public void setPhones(Set phones) {
        this.phones = phones;
    }




}


