package entity;
// Generated Mar 4, 2019, 5:23:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private BigDecimal projectid;
     private Employee employee;
     private String tipo;
     private String nombre;
     private BigDecimal budget;
     private Set projectemployees = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(BigDecimal projectid, String tipo, String nombre) {
        this.projectid = projectid;
        this.tipo = tipo;
        this.nombre = nombre;
    }
    public Proyecto(BigDecimal projectid, Employee employee, String tipo, String nombre, BigDecimal budget, Set projectemployees) {
       this.projectid = projectid;
       this.employee = employee;
       this.tipo = tipo;
       this.nombre = nombre;
       this.budget = budget;
       this.projectemployees = projectemployees;
    }
   
    public BigDecimal getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(BigDecimal projectid) {
        this.projectid = projectid;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getBudget() {
        return this.budget;
    }
    
    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }
    public Set getProjectemployees() {
        return this.projectemployees;
    }
    
    public void setProjectemployees(Set projectemployees) {
        this.projectemployees = projectemployees;
    }




}


